---
- name: show version
  hosts: all
  gather_facts: false
  #connection: local
  connection: network_cli
  #remote_user: admin
  #become: yes
  #become_method: enable

  vars:
    ansible_network_os: ios

    #cli:
     # host: "{{ ansible_host }}"
     # username: "{{ ansible_user }}"
     # password: "{{ ansible_password }}"

  tasks:
    - name: show version
      ios_command: 
        commands: show version
        #provider: "{{ cli }}"
      
      register: output

    - name: show output
      debug:
        var: output.stdout_lines
   
    - name: copy output to file
      copy: content="{{ output.stdout_lines }}" dest=./output/{{ inventory_hostname }}.txt

