---
- name: IOS Ping
  hosts: "{{ usersrc }}"
  gather_facts: false
  connection: network_cli 

  vars: 
    ansible_network_os: ios

  tasks:
    - name: IOS Ping
      ios_ping: 
        dest: "{{ userdest }}"
      
      register: output

    - name: show output
      debug:
        var: output
   

