---
- name: show version
  hosts: all
  gather_facts: false
  connection: network_cli

  vars: 
    ansible_network_os: ios

  tasks:
    - name: show version
      ios_command: 
        commands: show int
      
      register: output

    - name: show output
      debug:
        var: output.stdout_lines
   
    - name: copy output to file
      copy: content="{{ output.stdout_lines }}" dest=./output/{{ inventory_hostname }}.txt

